language: php
env:
  global:
  - secure: dprB6lKW9M9qUP11JTKEG3eSQ+1kd4vjo2TYWqXRWEDvYSXAnMaddJqs05caQipSn/OtXGQow1oQyiM0Do39lA3vN24jOrEnky4GpNlPsEupg+7j7sWWkjmOvEE1R5TxZFzn/4qZ/ABrE6VTkXHA38HzuPPmbW95TFIR5LwsSQg=
  - secure: DV1aEdppPpM36FnZwHu4eAya2YdIwhkC957HLq+AjR8kRY/x7J1/qDlpaTRSqwRQDGR+5DX4VfxRX6hImG/zUcoy/DNSYXpls0T8QzbPAktCJXj3iYbCKCLUdvnDhINWB/5pv0UUrphkwZwWPuQjnD2lzew4wITH1rNDf+jVB5k=
  - secure: bW1diWR9Ol4ps5xVA/9vLE7N0RmzTWUnuFNNLiHt6IPmrJ/k1HzycOOwGe9eVEaDW0eLX98dQoS4uG8CWbFdReQCEKSvkGDxxOUxLiwqWH0nRyVJ12l3WPQf26540UJWOqmx3NqCKEQPigvNcFAv7q+nNQVLbkfl3XIjgyRFp+c=
sudo: false
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: hhvm
  - php: 5.3
  - php: 5.4
  - php: 5.5
  - php: 5.6
  - php: 7.0
  allow_failures:
  - php: hhvm
  fast_finish: true
before_install:
- composer self-update
- composer config -g github-oauth.github.com $GITHUB_COMPOSER_TOKEN
install:
- composer install --prefer-dist --no-interaction --optimize-autoloader
script:
- vendor/bin/phpunit --exclude-group no-travis
after_script:
- vendor/bin/test-reporter
- vendor/bin/codacycoverage clover build/logs/clover.xml
